version: '3.4'

networks:
  crv_prod_network:
    driver: bridge

services:
  mysql-prod:
    container_name: mysql-prod
    image: mysql:8.0.13
    env_file:
      - ../.env.prod
    volumes:
      - ../DockerComposer/volumes/mysql/prod/database:/var/lib/mysql
      - ../DockerComposer/logs/prod/mysql:/var/log/Mysql
    networks:
      crv_prod_network:
        aliases:
        - mysql
    ports:
    - "3306:3306"
  ecommerce-prod:
    image: fiser/base-docker-microservices:ecommerce
    container_name: ecommerce-prod
    build:
      context: ../
      dockerfile: ./Docker/nginx/Dockerfile
      target: ecommerce
      args:
        env: prod
    restart: always
    volumes:
      -  ../DockerComposer/logs/prod/ECommerce:/app/ECommerce/var/log
    networks:
      crv_prod_network:
        aliases:
          - ecommerce
    env_file:
      - ../.env.prod
    depends_on:
      - mysql-prod
  nginx-prod:
    image: fiser/base-docker-microservices:nginx
    container_name: nginx-server-prod
    build:
      context: ../
      dockerfile: ./Docker/nginx/Dockerfile
      target: nginx
      args:
        env: prod
    restart: always
    ports:
      - "80:80"
    volumes:
      - ../DockerComposer/logs/prod/Nginx:/var/log/nginx
    env_file:
      - ../.env.prod
    networks:
      crv_prod_network:
        aliases:
          - nginx
